config/routes.rb
Empower::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions


  root :to => 'quizzes#index'
  get "quiz/:id", controller: 'quiz', action: 'show'

  resources :quizzes
  resources :quiz_results

  match 'quiz/:id/start' => 'quiz_results#new', as: 'start_quiz'
  match 'quiz/:id/results' => 'quiz_results#results_page', as: 'results_page'
  match 'quiz/:id/ad' => 'quiz_results#ad_page', as: 'ad_page'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  load_and_authorize_resource
  before_filter :authorize, except: [:index]

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(params[:quiz])
    if @quiz.save
      redirect_to @quiz, notice: "Successfully created Quiz."
    else
      render :new
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    if @quiz.update_attributes(params[:quiz])
      redirect_to @quiz, notice: "Successfully updated Quiz."
    else
      render :edit
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to quizzes_url, notice: "Successfully destroyed Quiz."
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_answer_fields.html.erb
<div class="row">
  <div class="large-10 columns">
    <fieldset style="padding: 10px 0 0 0; margin: 3px 10px;">
        <div class="large-1 columns">
          <%= f.label :content, "Answer: ", class: "inline right" %>
        </div>
        <div class="large-8 columns left">
          <%= f.text_field :content %>
        </div>
        <div class="large-3 columns weight_select">
          <div class="large-3 columns">
            <%= f.label :weight, "Weight: ", class: "inline" %>
          </div>
          <div class="large-9 columns">
            <%= f.number_field :weight, placeholder: "custom" %>
          </div>
        </div>
    </fieldset>

  </div>  
  <div class="large-1 columns left" style="margin-top: 17px;">
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", '#', class: "remove_fields alert button tiny radius", style: "font-size: 11px;" %>
  </div>
</div>

app/views/quizzes/_form.html.erb
<div id="form">
  <%= form_for @quiz, html: {:class => "custom"} do |f| %>
    <% if @quiz.errors.any? %>
      <div id="error_explanation" class="alert">
        <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>
        <ul>
        <% @quiz.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div id="quiz_settings" style="border: solid #444 2px; margin-top: 30px; padding: 10px; font-size: 16px;">
      <div class="row">
        <div class="large-12 columns"><h3 style="margin: 0 0 10px 0">Quiz Settings</h3></div>
      </div>
      <div class="row">
        <div class="large-9 large-centered columns">
          <div class="large-1 columns">
            <%= f.label :name, "Name:", class: "right inline", style: "margin-right:5px;" %>
          </div>
          <div class="large-11 columns">
            <%= f.text_field :name %>
          </div>
        </div>
      </div>
      <div class="row" style="margin-top: 15px;">
        
        <div class="large-7 columns" style="padding: 0 15px 0 5px;">
          <div class="row collapse" style="margin-bottom: 15px;">
            <div class="large-3 columns">
              <%= f.label :live, "Live" do %>
                <%= f.check_box :live, style: "display: none" %> Live
              <% end %>
            </div>
            <div class="large-3 columns">
              <%= f.label :scoreable, id: "quiz_scoreable_label" do %>
                <%= f.check_box :scoreable, style: "display: none" %> Scoreable
              <% end %>
            </div> 
            <div class="large-3 columns left">
              <span id="image_result_box">
                <%= f.label :image_result, id: "quiz_image_result_label" do %>
                  <%= f.check_box :image_result, style: "display: none" %> Image Result
                <% end %>
              </span>
            </div>
          </div>

          <div class="row collapse">
            <div class="large-12 columns" id="image_result_uploader" style="display:none; border: dashed 1px #555; padding: 12px 7px 5px 7px; margin: 10px 0; line-height: 22px;">
              <% if @quiz.image_url == nil %>
                <div class="large-4 columns"><%= f.label :image_label, "Result Image: ", style: "margin-top: 4px; font-weight: bold" %></div>
                <div class="large-5 columns right"><%= f.file_field :image, style: "margin: 5px 0px 0px -104px; width: 320px;" %></div>
                <div class="large-3 columns"><%= f.label :image, "Choose File", class: "button radius small expand", style: "margin-left:-20px;" %></div>
              <% else %>               
                <div class="large-4 columns"><%= f.label :image_label, "New Result Image: ", style: "margin-top: 4px; font-weight: bold" %></div>               
                <div class="large-5 columns right"><%= f.file_field :image, style: "margin: 5px 0px 0px -104px; width: 320px;" %></div>
                <div class="large-3 columns"><%= f.label :image, "Choose File", class: "button radius small expand", style: "margin-left:-20px;" %></div>
                <div class="large-12 columns" style="margin-bottom: 8px;">
                  <div class="large-4 columns" style="font-size: 15px;">
                    <%= f.label :remove_image, id: "remove_image_label", style: "margin-top: 4px;" do %>
                      <%= f.check_box :remove_image, style: "display: none" %> Remove Current Image: 
                    <% end %>
                  </div>
                  <div class="large-8 columns" style="font-size: 14px; margin: 4px 0 0 0;">
                    <% if File.basename(@quiz.image.to_s).length < 44 %>
                      <%= File.basename(@quiz.image.to_s) %>
                    <% else %>
                      <%= "..."+File.basename(@quiz.image.to_s)[-45,44] %>
                    <% end %>
                  </div>
                </div>  
              <% end %>
            </div>
          </div>

          <div class="row" style="line-height: 30px; margin-top: 15px;">
            <div class="large-5 columns left" style="margin-right: 30px;">
              <%= f.label :header_type_image, id: "header_image_uploader_label" do %>
                <%= f.radio_button :header_type, "image", checked:"checked", style: "display: none" %> Upload Header Image
              <% end %>
            </div>
            <div class="large-3 columns left">
              <%= f.label :header_type_url, id: "header_url_label" do %>
                <%= f.radio_button :header_type, "url", style: "display: none" %> Header Url
              <% end %>
            </div>
          </div>
       
            
          <div class="row collapse" style="margin-bottom: 20px;">
            <div class="large-12 columns" id="header_image_uploader_input" style="border: dashed #444 1px; padding: 12px 7px 5px 7px; margin-bottom: 10px; line-height: 22px;">
              <% if @quiz.header_image_url == nil %>
                <div class="large-4 columns"><%= f.label :header_image_label, "Header Image: ", style: "margin-top: 4px; font-weight: bold" %></div>
                <div class="large-5 columns right"><%= f.file_field :header_image, style: "margin: 5px 0px 0px -104px; width: 320px;" %></div>
                <div class="large-3 columns"><%= f.label :header_image, "Choose File", class: "button radius small expand", style: "margin-left:-20px;" %></div>       
              <% else %>
                <div class="large-4 columns"><%= f.label :header_image_label, "New Header Image: ", style: "margin-top: 4px; font-weight: bold" %></div>              
                <div class="large-5 columns right"><%= f.file_field :header_image, style: "margin: 5px 0px 0px -104px; width: 320px;" %></div>
                <div class="large-3 columns"><%= f.label :header_image, "Choose File", class: "button radius small expand", style: "margin-left:-20px;" %></div>
                <div class="large-12 columns" style="margin-bottom: 8px;">
                  <div class="large-4 columns" style="font-size: 15px;">
                    <%= f.label :remove_header_image, id: "remove_header_image_label", style: "margin-top: 4px;" do %>
                      <%= f.check_box :remove_header_image, style: "display: none;" %> Remove Header Image:  
                    <% end %>
                  </div>
                  <div class="large-8 columns" style="font-size: 14px; margin: 4px 0 0 0;">
                    <% if File.basename(@quiz.header_image.to_s).length < 44 %>
                      <%= File.basename(@quiz.header_image.to_s) %>
                    <% else %>
                      <%= "..."+File.basename(@quiz.header_image.to_s)[-45,44] %>
                    <% end %>
                  </div>
                </div>  
              <% end %>
            </div>            
            <div class="large-12 columns" style="display:none" id="header_url_input">
              <div class="large-2 columns">
                <%= f.label :header_url, "Header Url:", class: "inline" %>
              </div>
              <div class="large-10 columns">
                <%= f.text_field :header_url %>
              </div>
            </div>
          </div>

          <div class="row collapse">
            <div class="large-2 columns">
              <%= f.label :ad_header, "Ad Header:", class: "inline" %>
            </div>
            <div class="large-10 columns">
              <%= f.text_field :ad_header, placeholder: "This will be a simple text header above the Ad" %>
            </div>
          </div>

          <div class="row collapse">
            <div class="large-2 columns">
              <%= f.label :ad_url, "Ad Url:", class: "inline" %>
            </div>
            <div class="large-10 columns">
              <%= f.text_field :ad_url %>
            </div>
          </div>

          <div class="row collapse">
            <div class="large-2 columns">
              <%= f.label :ad_text, "Ad Text:", class: "inline" %>
            </div>
            <div class="large-10 columns">
              <%= f.text_area :ad_text, placeholder: "Place any additional information about the Ad here. It will be displayed in paragraph form under the Ad." %>
            </div>
          </div>

          <div class="row collapse">
            <div class="large-2 columns">
              <%= f.label :ad_width, "Ad Width:", class: "inline" %>
            </div>
            <div class="large-3 columns">
              <div class="large-10 columns">
                <% if @quiz.ad_width == nil %>
                  <%= f.number_field :ad_width, value: 700, max: 900 %>
                <% else %>
                  <%= f.number_field :ad_width, value: @quiz.ad_width, max: 900 %>
                <% end %>
              </div>
              <div class="large-2 columns">
                <span class="postfix radius">px</span>
              </div>
            </div>
            <div class="large-2 large-offset-2 columns">
              <%= f.label :ad_height, "Ad Height:", class: "inline" %>
            </div>
            <div class="large-3 columns">
              <div class="large-10 columns">
                <% if @quiz.ad_height == nil %>
                  <%= f.number_field :ad_height, value: 525 %>
                <% else %>
                  <%= f.number_field :ad_height, value: @quiz.ad_height %>
                <% end %>
              </div>
              <div class="large-2 columns">
                <span class="postfix radius">px</span>
              </div>
            </div>
          </div>

          <div class="row collapse" style="margin-top: 20px;">
            <%= f.label :ground_rules, "Ground Rules:  (Will be displayed as HTML code)" %>
            <div class="large-12 columns">
              <%= f.text_area :ground_rules, style: "height: 80px" %>
              
            </div>
          </div>

          <div class="row collapse">
            <%= f.label :fb_text, "Message to be used when posting results to Facebook:" %>
            <div class="large-12 columns">
              <%= f.text_field :fb_text %>
              <p style="font-size: 13px;">Example: "My life is worth approximately: $" <span style="color: #0ECF28">(calculated score goes here)</span></p>
            </div>
          </div>
        </div>
        <% if @quiz.image.to_s == "" && @quiz.header_image.to_s == "" && @quiz.header_url.to_s == "" %>
        <% else %>
          <div class="large-5 columns" style="border: #999 2px solid; min-height: 200px; padding: 20px 0;">
            <% unless @quiz.image_result == false %>
              <div class="row">
                <div class="large-11 large-centered columns" style="text-align:center">
                  <h6 style="margin-bottom:0">Current Result Image</h6>
                  <% if @quiz.image.to_s == "" %>
                    <h5 style="border: 1px dotted #555; margin: 4px 15px; padding: 50px 4px;"> None Uploaded </h5>
                  <% else%>
                    <%= image_tag @quiz.image_url() %>
                  <% end %>                
                </div>
              </div>
            <% end %>
            <div class="row">
              <div class="large-11 large-centered columns" style="text-align:center">
                <h6 style="margin: 25px 0px 0px 0px">Current Header Image</h6>
                <div id="current_header_url" style="display: none">
                  <% if @quiz.header_url == "" %>
                    <h5 style="border: 1px dotted #555; margin: 4px 15px; padding: 50px 4px;"> None Given </h5>
                  <% else%>
                    <%= image_tag @quiz.header_url %>
                  <% end %>
                </div>
                <div id="current_header_image" style="display: none">
                  <% if @quiz.header_image.to_s == "" %>
                    <h5 style="border: 1px dotted #555; margin: 4px 15px; padding: 50px 4px;"> None Uploaded </h5>
                  <% else%>
                    <%= image_tag @quiz.header_image_url() %>
                  <% end %>
                </div>              
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.fields_for :questions do |builder| %>
      <%= render 'question_fields', f: builder %>      
    <% end %>

    <div class="row" id="add_field_here">
      <div class="large-2 columns large-centered" style="margin-top: 20px; text-align:center">
        <%= link_to_add_fields "Add Question", f, :questions, "button radius success" %>
      </div>
    </div>

    <div class="large-12 columns" style="margin-top: 40px;">
      <div class="large-2 columns">
        <%= link_to 'Cancel', quizzes_path, class: "large button radius alert" %>
      </div>
      <div class="large-4 columns left large-offset-2">
        <%= f.submit "Submit", class: "large button expand radius" %>
      </div>
  <% end %>
</div>

app/views/quizzes/_question_fields.html.erb
<div class="row" style="font-size: 14px;">
  <fieldset>
    <div class="row">
      <div class="large-1 columns">
        <%= f.label :content, "Question: ", class: "inline right" %>
      </div>
      <div class="large-9 columns">
        <%= f.text_area :content, style: "height: 60px; margin-top: 5px;" %>
      </div>
      <div class="large-2 columns">
        <%= f.label :_destroy, class: "right inline" do %>
          <%= f.check_box :_destroy, style: "display: none" %> Remove Question
        <% end %>
      </div>
    </div>
    <div class="row">
      <%= f.fields_for :answers do |builder| %>
        <%= render 'answer_fields', f: builder %>
      <% end %>
      <div id="add_field_here">
        <div class="large-5 large-centered columns" style="padding-top: 10px;">
          <%= link_to_add_fields "Add Answer", f, :answers, "small button radius secondary" %>
        </div>
      </div>
    </div>
  </fieldset>

    
</div>

app/views/quizzes/edit.html.erb
<% content_for :title do %>
  Empowered Quizzes: <%= @quiz.name %>
<% end %>

<h1>Editing Survey</h1>

<%= render "form" %>

app/views/quizzes/index.html.erb
<% content_for :title do %>
  Empowered Quizzes
<% end %>

<h1>Quizzes</h1>
<h3> Please click on a quiz to take it</h3><br>

<% if can? :manage, Quiz %>
  <h4 style="text-align:center"><%= link_to 'Create a New Quiz', new_quiz_path, class: "small button radius", style: "color: #f1f1f1;" %></h4>
<% end %>

<% if can? :manage, Quiz %>
  <table style="margin: 0 auto; padding: 5px;">
    <tr>
      <th>Live?</th>
      <th>Name</th>
      <th>Number of Questions</th>
      <th>Scored?</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>

    <% @quizzes.each do |quiz| %>
    <tr>
      <td><% if quiz.live == true %>Yes<% else %>No<% end %></td>
      <td style="font-size: 18px; padding: 10px 10px; spacing: 5px 0px"><%= link_to quiz.name, start_quiz_path(quiz), style: "text-decoration:none; color: #333" %></td>
      <td><%= pluralize(quiz.questions.size, "Question") %></td>
      <td><% if quiz.scoreable == true %>Yes<% else %>No<% end %></td>
      <td><%= quiz.created_at.strftime("%b %e, %Y") %></td>
      <td style="border:none; width: 115px;"><%= link_to 'Show', quiz, class: "tiny secondary button radius", style: "font-size: 11px;" %>
      <%= link_to 'Edit', edit_quiz_path(quiz), class: "tiny secondary button radius", style: "font-size: 11px;" %></td>
      <% if can? :destroy, quiz %>
        <td style="border:none;"><%= link_to 'Destroy', quiz, class: "tiny alert button radius", style: "font-size: 11px;", method: :delete, data: { confirm: 'Are you sure? If you delete this quiz, you will also delete all results for this quiz.' } %></td>
      <% else %>
        </td>
      <% end %>

    </tr>
    <% end %>

  </table>
  <br><br>
<% else %>
  <% @quizzes.each do |quiz| %>
    <% if quiz.live == true %>
      <div style="font-size: 18px; margin: 15px 10px; padding: 5px 10px; width: 289px; min-height: 70px; float: left; text-align:center;  border: solid 2px #999">
        <b style="font-size: 24px; "><%= link_to quiz.name, start_quiz_path(quiz), style: "text-decoration:none; color: #333" %></b>
        <br>(<%= pluralize(quiz.questions.size, "Question") %>)
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/quizzes/new.html.erb
<% content_for :title do %>
  Empowered Quizzes: New Quiz
<% end %>

<h1>New Survey</h1>

<%= render "form" %>

app/views/quizzes/show.html.erb
<% content_for :title do %>
  Empowered Quizzes: <%= @quiz.name %>
<% end %>

<div class="row">
  <% if @quiz.header_image.file != nil %>
    <div class="large-11 large-centered columns" style="text-align: center">
      <%= image_tag @quiz.header_image_url() %>
    </div>      
  <% elsif @quiz.header_url != "" %>
    <div class="large-11 large-centered columns" style="text-aling:center; margin: 0 auto;">
      <%= image_tag(@quiz.header_url) %>
    </div>
  <% else %>
    <div class="large-11 large-centered columns">
      <h1 style="font-size: 26px;"><%= @quiz.name %></h1>
    </div>
  <% end %>
</div>

<div class="row" style="margin: 20px 0;">
  <div class="large-8 columns">
    <div style="padding: 0px 20px; border: dashed 1px #444;">
      <ol class="questions">
      <% @quiz.questions.each do |question| %>
        <li>
          <%= question.content %>
          <ol class="answers">
            <% question.answers.each do |answer| %>
              <li><%= answer.content %></li>
            <% end %>
          </ol>
        </li>
      <% end %>
      </ol>
    </div>
  </div>

  <div class="large-4 columns">
    <div class="row">
      <div class="large-11 large-centered columns">
        <% if @quiz.image_result == true %>
          <div>
            <%= image_tag @quiz.image_url().to_s %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class"row">
  <div class="large-3 columns">

    <div class="large-8 columns">
      <%= link_to 'Back to Quizzes', quizzes_path, class: "button radius" %>
    </div>
    <div class="large-4 columns">
      <%= link_to 'Edit', edit_quiz_path(@quiz), class: "button radius" %>
    </div>
  </div>
</div>