config/routes.rb
Empower::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions


  root :to => 'quizzes#index'
  get "quiz/:id", controller: 'quiz', action: 'show'

  resources :quizzes
  resources :quiz_results

  match 'quiz/:id/start' => 'quiz_results#new', as: 'start_quiz'
  match 'quiz/:id/results' => 'quiz_results#results_page', as: 'results_page'
  match 'quiz/:id/ad' => 'quiz_results#ad_page', as: 'ad_page'

end

app/models/quiz_result.rb
class QuizResult < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :questions
  belongs_to :quiz
  accepts_nested_attributes_for :questions, allow_destroy: true

end

app/controllers/quiz_results_controller.rb
class QuizResultsController < ApplicationController

  load_and_authorize_resource :except => :results_page
  before_filter :authorize, only: [:index, :show, :destroy]

  def index
    @quiz_results = QuizResult.all
  end

  def show
    @quiz_result = QuizResult.find(params[:id])
    @quiz_taken = Quiz.find(@quiz_result.quiz_id)
    @the_results = JSON.parse(@quiz_result.result, :symbolize_names => true)
  end

  def results_page
    @quiz_result = QuizResult.find(params[:id])
    @quiz_taken = Quiz.find(@quiz_result.quiz_id)
    @the_results = JSON.parse(@quiz_result.result, :symbolize_names => true)
    @score = 0
    @the_results.each do |r|
      unless r[:weight] == nil
        @score = @score + r[:weight]
      end
    end
  end

  def ad_page
    @quiz_taken = Quiz.find(@quiz_result.quiz_id)
  end

  def new
    @quiz_result = QuizResult.new
    @quiz_given = Quiz.find(params[:id])
  end

  def create
    @quiz_result = QuizResult.new(params[:quiz_result])
    @quiz_result.quiz_id = params[:quiz_taken].to_i
    @quiz_taken = Quiz.find(@quiz_result.quiz_id)
    
    @result_array = []
    c = params[:question_count].to_i                  # Determines number of questions on the survey
    1.upto(c) do |i|                                  # Loops through each question
      p = params["question_#{i}"]
      unless p == nil
        eval = eval(p)                                  # Changes param from a sting to a hash
        @result_array << eval                           # Adds the hash to the results array
      end
    end

    @quiz_result.result = @result_array.to_json

    respond_to do |format|
      if @quiz_result.save
        if @quiz_taken.ad_url != ""
          format.html { redirect_to ad_page_path(@quiz_result) }
        elsif @quiz_taken.image_result == true
          format.html { redirect_to results_page_path(@quiz_result) }
        else
          format.html { redirect_to @quiz_result }
          # first need to create quiz_thank_you_path before below line will work
          #format.html { redirect_to quiz_thank_you_path }
        end
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @quiz_result = QuizResult.find(params[:id])
    @quiz_result.destroy

    respond_to do |format|
      format.html { redirect_to quiz_results_url }
    end
  end

end

app/views/quiz_results/_form.html.erb
<div class="row">
  <% if @quiz_given.header_image.file != nil %>
    <div class="large-11 large-centered columns" style="text-align: center">
      <%= image_tag @quiz_given.header_image_url() %>
    </div>      
  <% elsif @quiz_given.header_url != "" %>
    <div class="large-11 large-centered columns" style="text-aling:center; margin: 0 auto;">
      <%= image_tag(@quiz_given.header_url) %>
    </div>
  <% else %>
    <div class="large-11 large-centered columns">
      <h1 style="font-size: 26px;"><%= @quiz_given.name %></h1>
    </div>
  <% end %>
</div>

<div style="width: 850px; margin: 0 auto;">
  <%= form_for @quiz_result, html: {:class => "custom"} do |f| %>
    <% if @quiz_result.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@quiz_result.errors.count, "error") %> prohibited this Quiz from being saved:</h2>
        <ul>
        <% @quiz_result.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <div class="row">
      <% unless @quiz_given.ground_rules == "" %>
        <h3 style="margin: 15px 0 0 0; font-size: 18px;">Ground Rules</h3>
        <div style=" width: 650px; margin: 0 auto 20px auto; border: solid #777 2px; min-height: 80px; padding: 8px 14px; font-size: 14px; line-height: 20px;">
          <%= render :inline => @quiz_given.ground_rules %>
        </div>
      <% end %>
    </div>

    <div class="row" style="border: dashed 1px #444; padding: 8px 20px;">
      <div class="large-12 columns">
        <ol class="questions">
          <% @question_count = 0 %>
          <% @quiz_given.questions.each do |question| %>
            <% @question_count = @question_count + 1 %>
            <div class="large-12 columns" style="margin-bottom: 20px;">
              <li>
                <h5 style="font-size: 13px; margin-bottom: 3px;"><%= question.content %></h5>
                <ol class="answers">            
                  <% question.answers.each do |answer| %>
                    <%= f.label :"#{answer.content}" do %>
                      <% answer_hash = {answer: answer.content, weight: answer.weight, question_number: @question_count} %> 
                      <div class="large-1 columns">
                        <%= f.radio_button :result, answer_hash, style: "margin: 5px; font-weight: normal; display: none", class: "answers", name: "question_#{@question_count}" %>
                      </div>
                      <div class="large-11 columns" style="font-size: 14px; margin: 0 0 0 -35px;">
                        <%= label_tag :result, answer.content %>
                      </div>
                      <br>
                    <% end %>
                  <% end %>
                </ol>
              </li>
            </div>
          <% end %>
        </ol>
      </div>
    </div>
    <div class="row">
      <%= hidden_field_tag 'question_count', @question_count %> 
      <%= hidden_field_tag 'quiz_taken', @quiz_given.id %> 
      <div class="actions" style="text-align:center">
        <%= f.submit "Submit Quiz", disabled: "disabled", :id => "submit_button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/quiz_results/ad_page.html.erb
<% content_for :title do %>
  Empowered Quizzes
<% end %>

<div class="row">
  <div class="large-12 large-centered columns">
    <h3><%= @quiz_taken.ad_header %></h3>
    <div style="margin: 0 auto; width: <%= @quiz_taken.ad_width %>px;">
      <iframe width="<%= @quiz_taken.ad_width %>" height="<%= @quiz_taken.ad_height %>" style=" border: solid #444 3px;" src=<%= @quiz_taken.ad_url %> frameborder="0" allowfullscreen></iframe>
      <div class=" large-12 large-centered columns" style="margin: 5px 0 35px 0; border: solid 2px #555; border-radius: 10px; padding: 7px 14px;">
        <p style="font-size: 16px;"><%= @quiz_taken.ad_text %></p>
      </div>
    <% if @quiz_taken.image_result == true %>
      <%= link_to "Continue to Quiz Results", results_page_path(@quiz_result), class: "button radius expand large" %>
    <% else %>
      <h2> Thank you for taking our quiz! </h2>
    <% end %>
  </div>
</div>

app/views/quiz_results/index.html.erb
<% content_for :title do %>
  Empowered Quiz Results
<% end %>

<h1>Listing Quizzes Taken</h1>

<table style="margin: 0 auto">
  <tr>
    <th>Score</th>
    <th>Survey Name</th>
    <th>Date Taken</th>
    <th></th>
    <th></th>
  </tr>

<% @quiz_results.each do |quiz_result| %> 
  <% @the_results = JSON.parse(quiz_result.result, :symbolize_names => true) %>
  <tr>

    <% score = 0 %>
    <% @the_results.each do |result| %>
      <% if result[:weight] != nil %>
        <% score = score + result[:weight] %>
      <% end %>
    <% end %>
    <td><% if Quiz.find(quiz_result.quiz_id).scoreable == true %><%= score %><% else %>n/a<% end %></td>
    <td><%= Quiz.find(quiz_result.quiz_id).name %></td>
    <td style="width: 120px;"><%= quiz_result.created_at.strftime("%b %e, %Y") %></td>
    <td style="border: none"><%= link_to 'Show', quiz_result, class: "tiny secondary button radius", style: "font-size: 11px;"  %></td>
    <% if can? :destroy, QuizResult %>
      <td style="border: none"><%= link_to 'Destroy', quiz_result, class: "tiny alert button radius", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/quiz_results/new.html.erb
<% content_for :title do %>
  Empowered Quizzes: <%= @quiz_given.name %>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path, class: "button radius" %>

app/views/quiz_results/results_page.html.erb
<% content_for :title do %>
  Empowered Quizzes: <%= @quiz_taken.name %> (<%= @score.to_s %>)
<% end %>

<% app_id = "1111125565694052" %>
<% display = "popup" %>
<% link = "https://empowered-quizzes.herokuapp.com"+start_quiz_path(@quiz_taken).to_s %>
<!-- Static image for all quizzes -->
<% picture = 'http://commondatastorage.googleapis.com/quiz-result-images/fb%20icon%20for%20empowered.jpg' %>
<!-- Different image for each quiz -->
<%# picture = @quiz_taken.image_url().to_s %>
<% name = @quiz_taken.name.gsub("'", "%27") %>
<% caption = "Click the link above to get your own score!" %>
<% description = @quiz_taken.fb_text.gsub("'", "%27") + " " + @score.to_s %>
<%# redirect_uri = results_page_url(@quiz_result)+"/#close_window" %>
<% redirect_uri = "https://empowered-quizzes.herokuapp.com"+start_quiz_path(@quiz_taken).to_s %>

<script>
  function fbs_click() {
    u=location.href;
    t=document.title;window.open('https://www.facebook.com/dialog/feed?app_id=<%= app_id %>&display=<%= display %>&link=<%= link %>&picture=<%= picture %>&name=<%= name %>&caption= <%= caption %>&description= <%= description %>&redirect_uri= <%= redirect_uri %>','Facebook Feed Post','width=600, height=320, left=150, top=150');
    return false;
  }
  //if (window.location.hash == '#close_window') 
    //window.top.close()
    //alert(window.location.hash)
    
</script>
<style> 
  .fb_share_link { 
    padding: 4px 0 4px 35px;
    height: 35px; 
    background:url(http://commondatastorage.googleapis.com/quiz-result-images/facebook%20share%20icon.jpg) no-repeat top left;
    background-size: 30px 30px;
  }

  #image_background{
    display: block;
    background: url('<%= @quiz_taken.image_url().to_s %>') no-repeat; 
    width: 300px; 
    font-size: 35px;
    color: #fff; 
    text-decoration: none;
    text-align: center;
    padding-top: 160px;
    padding-bottom: 35px;
    margin: 10px auto;

  }
</style>

<div class="row">
  <div class="large-11 large-centered columns" id="image_background">
    <%= @score %>
  </div>
</div>

<div class="row">
  <div class="large-4 large-centered columns" style="text-align:center; font-size: 20px;">
    <div style="  padding: 20px;" style="border: solid 1px blue; padding: 10px;">
      <a href="#" onclick="fbs_click()" target="_new" class="fb_share_link">Share on Facebook</a>
    </div>
    
  </div>
</div>

<div class="row">
  <div class="large-3 large-centered columns" style="text-align:center">
    <%= link_to "Return to Full List of Quizzes", quizzes_path %>
  </div>
</div>

app/views/quiz_results/show.html.erb
<% content_for :title do %>
  Empowered Quizzes: <%= @quiz_taken.name %>
<% end %>

<h1><%= @quiz_taken.name %></h1>

<div style="margin: 10px; padding: 0px 20px; border: dashed 1px #444">
  <ol class="questions">
    <% i = 0 %>
    <% score = 0 %>    

    <% @quiz_taken.questions.each do |question| %>  
      <% answer_count = 0 %>
      <% incorrect_answer_count = 0 %> 
      <li>
        <% if @the_results[i] %>          

          <% question.answers.each do |answer| %>
            <% answer_count += 1 %>
            <% if i+1 == @the_results[i][:question_number] && answer.content != @the_results[i][:answer] %>
              <% incorrect_answer_count += 1 %>
            <% end %>
          <% end %>
          <% if answer_count == incorrect_answer_count %>
            <%= question.content %><span style="color: red; font-size: 12px;"> (Question was not present when quiz was taken)</span>
            <ol class="answers">
              <% question.answers.each do |answer| %>
                <li><%= answer.content %></li>
              <% end %>
            </ol>  
          <% else %>
            <%= question.content %>
            <ol class="answers">
              <% question.answers.each do |answer| %>
                <% if i+1 == @the_results[i][:question_number] && answer.content == @the_results[i][:answer] %>
                  <li><span id="chosen_answer"> <%= answer.content %> </span></li>
                  <% unless @the_results[i][:weight] == nil %>
                    <% score = score + @the_results[i][:weight] %>
                  <% end %>
                <% else %>
                  <li><%= answer.content %></li>
                <% end %>         
              <% end %>
            </ol>
          <% end %>
          
        <% else %>          
          <%= question.content %><span style="color: red; font-size: 12px;"> (Question was not present when quiz was taken)</span>
          <ol class="answers">
            <% question.answers.each do |answer| %>
              <li><%= answer.content %></li>
            <% end %>
          </ol>          
        <% end %>
      </li>
      <% i += 1 %>
    <% end %>
  </ol>
  <% if @quiz_taken.scoreable == true %>
    <h4 style="text-align:center">Total Score: <%= score %></h4><br>
  <% end %>
  
</div>
<br><br>
<div class"row">
  <div class="large-3 columns">
    <div class="large-4 columns">
      <%= link_to 'Back', quiz_results_path, class: "button radius" %>
    </div>
    <div class="large-7 columns">
      <% if @quiz_taken.image_result == true %><%= link_to 'Result Image', results_page_path(@quiz_result), class: "button radius" %><% end %>
    </div>
  </div>
</div>